# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: change_wishlist.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63hange_wishlist.proto\"\"\n\x08Wishlist\x12\x16\n\x05value\x18\x01 \x01(\x0b\x32\x07.Garena\"-\n\x06Garena\x12\x0f\n\x07item_id\x18\x01 \x01(\x03\x12\x12\n\ngarena_420\x18\x02 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'change_wishlist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WISHLIST']._serialized_start=25
  _globals['_WISHLIST']._serialized_end=59
  _globals['_GARENA']._serialized_start=61
  _globals['_GARENA']._serialized_end=106
# @@protoc_insertion_point(module_scope)
