# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wishlist.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ewishlist.proto\"+\n\x04Item\x12\x0e\n\x06itemId\x18\x01 \x01(\x05\x12\x13\n\x0breleaseTime\x18\x02 \x01(\x05\"\x1d\n\x05Items\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Itemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wishlist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEM']._serialized_start=18
  _globals['_ITEM']._serialized_end=61
  _globals['_ITEMS']._serialized_start=63
  _globals['_ITEMS']._serialized_end=92
# @@protoc_insertion_point(module_scope)
